### ISSUE TITLE
Do not require explicit use of internal access modifier

### ISSUE THREAD

**Issue by haidalinda** [prolificinteractive/swift-style-guide#47]
I understand our goal with requiring the `internal` access modifier is consistency, but I think it hurts more than it helps.

A few reasons:
* It goes against Swift/community convention
* It adds visual clutter
* It's a waste of time in code review to point out/correct when `internal` is missing
* Developer's inheriting a project in this style will likely not use `internal`, so the usage of it will not be uniformly applied in due time

**Comment by ThibaultKlein** [comment]
I think it makes sense to remove this rule now that Swift has been adopted and conventions have been growing in the community.

The original rationale was to make very clear that internal was the default access for everything, but now that Swift has been around for couple years it might be time to assume that everybody knows it. And on top of that, I can't argue with the reasons you provided.

@htinlinn @phillfarrugia @paulmiard any thoughts on that?

**Comment by htinlinn** [comment]
The changes proposed in this issue have been addressed in #50.
